param(
    # Directory containing meta.json, groups.json and types.json from EVE Ref.
    [Parameter(Mandatory = $true)][string]$ReferenceDirectory,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
if (-not $OutputPath) { $OutputPath = Join-Path $PSScriptRoot '..\src\data\NPCGeneralNames.ahk' }
$referenceRoot = (Resolve-Path -LiteralPath $ReferenceDirectory).Path
$meta = Get-Content -Raw -Encoding UTF8 (Join-Path $referenceRoot 'meta.json') | ConvertFrom-Json
$groups = Get-Content -Raw -Encoding UTF8 (Join-Path $referenceRoot 'groups.json') | ConvertFrom-Json
$entityGroups = @{}
foreach ($property in $groups.PSObject.Properties) {
    if ($property.Value.category_id -eq 11) { $entityGroups[[int]$property.Name] = $true }
}
if ($entityGroups.Count -eq 0 -or -not $meta.build_time) { throw 'Invalid reference dataset.' }

# Do not filter on published: almost every combat NPC is unpublished.
$typesPath = Join-Path $referenceRoot 'types.json'
$types = Get-Content -Raw -Encoding UTF8 $typesPath | ConvertFrom-Json
$names = [Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
$typeCount = 0
foreach ($property in $types.PSObject.Properties) {
    $type = $property.Value
    if (-not $entityGroups.ContainsKey([int]$type.group_id)) { continue }
    $name = [string]$type.name.en
    if ([string]::IsNullOrWhiteSpace($name) -or $name -match '[\r\n]') {
        throw "Invalid English name for entity type $($property.Name)."
    }
    [void]$names.Add($name)
    $typeCount++
}
if ($typeCount -lt 1000) { throw 'Unexpectedly small Entity dataset; output was not replaced.' }

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('; Generated by tools/Update-NPCNames.ps1. Do not edit by hand.')
$lines.Add('; Source: https://data.everef.net/reference-data/reference-data-latest.tar.xz')
$lines.Add("; Source build: $($meta.build_time)")
$lines.Add("; types.json SHA256: $((Get-FileHash -LiteralPath $typesPath -Algorithm SHA256).Hash.ToLowerInvariant())")
$lines.Add("; Entity category 11: $typeCount types, $($names.Count) distinct English names.")
$lines.Add('; Includes unpublished entities; names and game data belong to CCP hf.')
$lines.Add('class NPCGeneralNames {')
$lines.Add('    static AddTo(names) {')
# Bound each continuation section well below AutoHotkey expression limits.
$chunk = [Collections.Generic.List[string]]::new()
$chunkLength = 0
function Add-Chunk {
    $lines.Add('        for name in StrSplit("')
    $lines.Add('(')
    foreach ($entry in $chunk) { $lines.Add($entry) }
    $lines.Add(')", "`n", "`r")')
    $lines.Add('            names[name] := true')
    $chunk.Clear()
}
foreach ($name in $names) {
    # Escape AHK literals, including the continuation-section closing character.
    $escaped = $name.Replace('`', '``').Replace('"', '`"')
    if ($escaped.StartsWith(')')) { $escaped = '`' + $escaped }
    if ($chunkLength + $escaped.Length + 1 -gt 6000) { Add-Chunk; $chunkLength = 0 }
    $chunk.Add($escaped)
    $chunkLength += $escaped.Length + 1
}
if ($chunk.Count) { Add-Chunk }
$lines.Add('    }')
$lines.Add('}')
$outputFullPath = [IO.Path]::GetFullPath($OutputPath)
[void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outputFullPath))
# BOM preserves diamond and other non-ASCII NPC names in AutoHotkey source.
[IO.File]::WriteAllText($outputFullPath, ($lines -join "`r`n") + "`r`n", [Text.UTF8Encoding]::new($true))
Write-Output "Generated $($names.Count) distinct names from $typeCount entity types ($($meta.build_time))."
