param(
    [Parameter(Mandatory = $true)][string]$ReferenceDirectory,
    [string]$OutputPath
)
$ErrorActionPreference = 'Stop'
if (-not $OutputPath) { $OutputPath = Join-Path $PSScriptRoot '..\src\data\DamageProfiles.ahk' }
$root = (Resolve-Path -LiteralPath $ReferenceDirectory).Path
$meta = Get-Content -Raw -Encoding UTF8 (Join-Path $root 'meta.json') | ConvertFrom-Json
$attributes = Get-Content -Raw -Encoding UTF8 (Join-Path $root 'dogma_attributes.json') | ConvertFrom-Json
$attributeIds = @(114, 118, 117, 116) # EM, thermal, kinetic, explosive damage (not resistance).
$attributeNames = @('emDamage', 'thermalDamage', 'kineticDamage', 'explosiveDamage')
for ($index = 0; $index -lt 4; $index++) {
    if ($attributes.([string]$attributeIds[$index]).name -ne $attributeNames[$index]) {
        throw 'Unexpected damage attribute schema.'
    }
}
$fighterAttributeSets = @(
    @(2171, 2172, 2173, 2174), # Fighter turret attack
    @(2227, 2228, 2229, 2230), # Fighter missile attack
    @(2131, 2132, 2133, 2134), # Fighter missile ability / salvo
    @(2325, 2326, 2327, 2328)  # Fighter kamikaze ability
)
$fighterAttributePrefixes = @('fighterAbilityAttackTurretDamage', 'fighterAbilityAttackMissileDamage', 'fighterAbilityMissilesDamage', 'fighterAbilityKamikazeDamage')
$fighterSuffixes = @('EM', 'Therm', 'Kin', 'Exp')
for ($setIndex = 0; $setIndex -lt $fighterAttributeSets.Count; $setIndex++) {
    for ($index = 0; $index -lt 4; $index++) {
        if ($attributes.([string]$fighterAttributeSets[$setIndex][$index]).name -ne ($fighterAttributePrefixes[$setIndex] + $fighterSuffixes[$index])) {
            throw 'Unexpected fighter damage attribute schema.'
        }
    }
}
# Missiles use the four damage-family names in DPSMeter instead of item rows.
$smartbombMixes = @{
    EMP = @(1, 0, 0, 0); Plasma = @(0, 1, 0, 0)
    Graviton = @(0, 0, 1, 0); Proton = @(0, 0, 0, 1)
    Multispectrum = @(0.25, 0.25, 0.25, 0.25)
}
$typesPath = Join-Path $root 'types.json'
$types = Get-Content -Raw -Encoding UTF8 $typesPath | ConvertFrom-Json
$profiles = @{}
$ambiguous = @{}
$culture = [Globalization.CultureInfo]::InvariantCulture
foreach ($property in $types.PSObject.Properties) {
    $type = $property.Value
    if ($type.category_id -notin @(18, 87) -and $type.group_id -ne 72) { continue }
    $name = [string]$type.name.en
    if ([string]::IsNullOrWhiteSpace($name) -or $name -match '[|\r\n]') { throw 'Invalid type name.' }
    $damage = @($attributeIds | ForEach-Object { [double]$type.dogma_attributes.([string]$_).value })
    if ($type.category_id -eq 87) {
        # Fighters use ability-specific attributes, not the common damage
        # fields. A name-only match is safe only when all damaging abilities
        # have the same normalized mix. Otherwise leave the type unknown.
        foreach ($attributeSet in $fighterAttributeSets) {
            $abilityDamage = @($attributeSet | ForEach-Object { [double]$type.dogma_attributes.([string]$_).value })
            $abilityTotal = ($abilityDamage | Measure-Object -Sum).Sum
            if ($abilityTotal -le 0) { continue }
            $damageTotal = ($damage | Measure-Object -Sum).Sum
            if ($damageTotal -gt 0) {
                for ($index = 0; $index -lt 4; $index++) {
                    if ([math]::Abs($abilityDamage[$index] / $abilityTotal - $damage[$index] / $damageTotal) -gt 0.000000001) {
                        $ambiguous[$name] = $true
                    }
                }
            } else { $damage = $abilityDamage }
        }
    }
    $total = ($damage | Measure-Object -Sum).Sum
    if ($total -le 0) { continue }
    if ($type.group_id -eq 72 -and $name -match '\b(EMP|Plasma|Graviton|Proton|Multispectrum)\s+Smartbomb\b') {
        $expected = $smartbombMixes[$Matches[1]]
        for ($index = 0; $index -lt 4; $index++) {
            if ([math]::Abs($damage[$index] / $total - $expected[$index]) -gt 0.000000001) {
                throw "Smartbomb family damage changed for $name; review runtime mapping before regenerating."
            }
        }
        continue # Runtime family lookup replaces this item row.
    }
    $values = @($damage | ForEach-Object { $_.ToString('R', $culture) })
    $entry = ($values -join '|') + '|' + [int]($type.category_id -in @(18, 87))
    if ($profiles.ContainsKey($name) -and $profiles[$name] -ne $entry) { $ambiguous[$name] = $true }
    $profiles[$name] = $entry
}
foreach ($name in $ambiguous.Keys) { $profiles.Remove($name) }
if ($profiles.Count -lt 100) { throw 'Unexpectedly small damage dataset; output was not replaced.' }
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('; Generated by tools/Update-DamageProfiles.ps1. Do not edit by hand.')
$lines.Add('; Source: https://data.everef.net/reference-data/reference-data-latest.tar.xz')
$lines.Add("; Source build: $($meta.build_time)")
$lines.Add("; types.json SHA256: $((Get-FileHash -LiteralPath $typesPath -Algorithm SHA256).Hash.ToLowerInvariant())")
$lines.Add("; $($profiles.Count) exact names; $($ambiguous.Count) ambiguous names omitted. Game data belongs to CCP hf.")
$lines.Add('; Scope: drones, fighters and smartbomb exceptions. Missiles and smartbombs use family names in DPSMeter.')
$lines.Add('; Fields: name | EM | thermal | kinetic | explosive | drone-or-fighter')
$lines.Add('class DamageProfiles {')
$lines.Add('    static AddTo(profiles) {')
$chunk = [Collections.Generic.List[string]]::new()
$chunkLength = 0
function Add-Chunk {
    $lines.Add('        for row in StrSplit("')
    $lines.Add('(')
    foreach ($entry in $chunk) { $lines.Add($entry) }
    $lines.Add(')", "`n", "`r") {')
    $lines.Add('            fields := StrSplit(row, "|")')
    $lines.Add('            total := fields[2] + fields[3] + fields[4] + fields[5]')
    $lines.Add('            profiles[fields[1]] := {mix: [fields[2] / total, fields[3] / total, fields[4] / total, fields[5] / total], craft: fields[6] + 0}')
    $lines.Add('        }')
    $chunk.Clear()
}
foreach ($name in ($profiles.Keys | Sort-Object)) {
    $escaped = ($name + '|' + $profiles[$name]).Replace('`', '``').Replace('"', '`"')
    if ($escaped.StartsWith(')')) { $escaped = '`' + $escaped }
    if ($chunkLength + $escaped.Length + 1 -gt 6000) { Add-Chunk; $chunkLength = 0 }
    $chunk.Add($escaped)
    $chunkLength += $escaped.Length + 1
}
if ($chunk.Count) { Add-Chunk }
$lines.Add('    }')
$lines.Add('}')
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), ($lines -join "`r`n") + "`r`n", [Text.UTF8Encoding]::new($true))
Write-Output "Generated $($profiles.Count) damage profiles; $($ambiguous.Count) ambiguous names omitted."
