; Generated by tools/Update-DamageProfiles.ps1. Do not edit by hand.
; Source: https://data.everef.net/reference-data/reference-data-latest.tar.xz
; Source build: 2026-09-10T12:10:04Z
; types.json SHA256: 0ffb54c6a99af2b723632f10726426231ef22ba0812e093c5fe42d1785213525
; 178 exact names; 2 ambiguous names omitted. Game data belongs to CCP hf.
; Scope: drones, fighters and smartbomb exceptions. Missiles and smartbombs use family names in DPSMeter.
; Fields: name | EM | thermal | kinetic | explosive | drone-or-fighter
class DamageProfiles {
    static AddTo(profiles) {
        for row in StrSplit("
(
Acolyte I|20|0|0|0|1
Acolyte II|20|0|0|0|1
Ametat I|253|0|0|0|1
Ametat II|279|0|0|0|1
Antaeus I|0|293|0|0|1
Antaeus II|0|323|0|0|1
Arabellata SW-900-I|60|30|0|0|1
Aralez|0|38|58|0|1
Atlas SD-900-I|60|30|0|0|1
'Augmented' Acolyte|13|7|0|0|1
'Augmented' Berserker|0|0|29|35|1
'Augmented' Hammerhead|0|19|13|0|1
'Augmented' Hobgoblin|0|13|7|0|1
'Augmented' Hornet|0|7|13|0|1
'Augmented' Infiltrator|19|13|0|0|1
'Augmented' Ogre|0|35|29|0|1
'Augmented' Praetor|35|29|0|0|1
'Augmented' Valkyrie|0|0|13|19|1
'Augmented' Vespa|0|13|19|0|1
'Augmented' Warrior|0|0|7|13|1
'Augmented' Wasp|0|29|35|0|1
Baker_PLACEHOLDER|38|0|0|0|1
Berserker I|0|0|0|64|1
Berserker II|0|0|0|64|1
Bouncer I|0|0|0|64|1
Bouncer II|0|0|0|64|1
Caldari Navy Dragonfly|0|0|113.5|0|1
Caldari Navy Hornet|0|0|20|0|1
Caldari Navy Locust|0|0|42|0|1
Caldari Navy Vespa|0|0|32|0|1
Caldari Navy Warden|0|0|64|0|1
Caldari Navy Wasp|0|0|64|0|1
Charlie_PLACEHOLDER|65|0|0|0|1
Civilian Hobgoblin|0|10|0|0|1
Curator I|64|0|0|0|1
Curator II|64|0|0|0|1
Cyclops I|0|366|0|0|1
Cyclops II|0|404|0|0|1
Darter TP-600-I|30|15|0|0|1
Dog_PLACEHOLDER|253|0|0|0|1
Dragonfly I|0|0|108|0|1
Dragonfly II|0|0|118.5|0|1
Easy_PLACEHOLDER|316|0|0|0|1
Einherji I|0|0|0|93|1
Einherji II|0|0|0|102|1
Equite I|38|0|0|0|1
Equite II|42|0|0|0|1
FA-14 Templar|0|22|0|0|1
Federation Navy Firbolg|0|118.5|0|0|1
Federation Navy Garde|0|64|0|0|1
Federation Navy Hammerhead|0|32|0|0|1
Federation Navy Hobgoblin|0|20|0|0|1
Federation Navy Ogre|0|64|0|0|1
Federation Navy Satyr|0|44|0|0|1
Firbolg I|0|112.5|0|0|1
Firbolg II|0|124.5|0|0|1
Garde I|0|64|0|0|1
Garde II|0|64|0|0|1
Gecko|32|32|32|32|1
Gram I|0|0|0|36|1
Gram II|0|0|0|40|1
Gungnir I|0|0|0|239|1
Gungnir II|0|0|0|265|1
Hammerhead I|0|32|0|0|1
Hammerhead II|0|32|0|0|1
Hellhound I|0|56|0|0|1
Hobgoblin I|0|20|0|0|1
Hobgoblin II|0|20|0|0|1
Hornet I|0|0|20|0|1
Hornet II|0|0|20|0|1
Humboldt EC-900-I|60|30|0|0|1
Huntsman SW-600-I|30|15|0|0|1
Immaculate TD-600-I|30|15|0|0|1
Imperial Navy Acolyte|20|0|0|0|1
Imperial Navy Curator|64|0|0|0|1
Imperial Navy Equite|40|0|0|0|1
Imperial Navy Infiltrator|32|0|0|0|1
Imperial Navy Praetor|64|0|0|0|1
Imperial Navy Templar|103|0|0|0|1
Infiltrator I|32|0|0|0|1
Infiltrator II|32|0|0|0|1
Inshore EC-300-I|20|10|0|0|1
'Integrated' Acolyte|13|7|0|0|1
'Integrated' Berserker|0|0|29|35|1
'Integrated' Hammerhead|0|19|13|0|1
'Integrated' Hobgoblin|0|13|7|0|1
'Integrated' Hornet|0|7|13|0|1
'Integrated' Infiltrator|19|13|0|0|1
'Integrated' Ogre|0|35|29|0|1
'Integrated' Praetor|35|29|0|0|1
'Integrated' Valkyrie|0|0|13|19|1
'Integrated' Vespa|0|13|19|0|1
'Integrated' Warrior|0|0|7|13|1
'Integrated' Wasp|0|29|35|0|1
Locust I|0|0|40|0|1
Locust II|0|0|44|0|1
Luna SD-600-I|30|15|0|0|1
Malleus I|316|0|0|0|1
Malleus II|349|0|0|0|1
Mantis I|0|0|349|0|1
Mantis II|0|0|386|0|1
Meganeura TP-900-I|60|30|0|0|1
Micro Degenerative Concussion Bomb I|0|0|0|50|0
Micro 'Notos' Explosive Charge I|0|0|0|30|0
Micro Rudimentary Concussion Bomb I|0|0|30|0|0
Micro 'Vehemence' Shockwave Charge|30|0|0|0|0
Micro YF-12a Smartbomb|0|30|0|0|0
Mosquito EV-600-I|30|15|0|0|1
Nertic EC-600-I|30|15|0|0|1
Ogre I|0|64|0|0|1
Ogre II|0|64|0|0|1
Orbweaver SW-300-I|20|10|0|0|1
Praetor I|64|0|0|0|1
Praetor II|64|0|0|0|1
Repair Drone|0|0|4|2|1
Republic Fleet Berserker|0|0|0|64|1
Republic Fleet Bouncer|0|0|0|64|1
Republic Fleet Einherji|0|0|0|97.5|1
Republic Fleet Gram|0|0|0|38|1
Republic Fleet Valkyrie|0|0|0|32|1
Republic Fleet Warrior|0|0|0|20|1
Satyr I|0|42|0|0|1
Satyr II|0|46|0|0|1
Skimmer TP-300-I|20|10|0|0|1
Standup Ametat I|835|0|0|0|1
Standup Ametat II|921|0|0|0|1
Standup Antaeus I|0|967|0|0|1
Standup Antaeus II|0|1066|0|0|1
Standup Cyclops I|0|1208|0|0|1
Standup Cyclops II|0|1333|0|0|1
Standup Dragonfly I|0|0|187|0|1
Standup Dragonfly II|0|0|205|0|1
Standup Einherji I|0|0|0|161|1
Standup Einherji II|0|0|0|177|1
Standup Equite I|99|0|0|0|1
Standup Equite II|109|0|0|0|1
Standup Firbolg I|0|195|0|0|1
Standup Firbolg II|0|216|0|0|1
Standup Gram I|0|0|0|94|1
Standup Gram II|0|0|0|104|1
Standup Gungnir I|0|0|0|789|1
Standup Gungnir II|0|0|0|875|1
Standup Locust I|0|0|104|0|1
Standup Locust II|0|0|114|0|1
Standup Malleus I|1043|0|0|0|1
Standup Malleus II|1152|0|0|0|1
Standup Mantis I|0|0|1152|0|1
Standup Mantis II|0|0|1274|0|1
Standup Satyr I|0|109|0|0|1
Standup Satyr II|0|120|0|0|1
Standup Templar I|169|0|0|0|1
Standup Templar II|187|0|0|0|1
Standup Termite I|0|0|921|0|1
Standup Termite II|0|0|1020|0|1
Standup Tyrfing I|0|0|0|987|1
Standup Tyrfing II|0|0|0|1092|1
Stellate TD-300-I|20|10|0|0|1
Stigmella SD-300-I|20|10|0|0|1
'Subverted' JVN-UC49|32|32|32|32|1
Tabanida EV-900-I|60|30|0|0|1
Templar I|97.5|0|0|0|1
Templar II|108|0|0|0|1
Termite I|0|0|279|0|1
Termite II|0|0|309|0|1
Tick EV-300-I|20|10|0|0|1
Torafugu TD-900-I|60|30|0|0|1
Tyrfing I|0|0|0|299|1
Tyrfing II|0|0|0|331|1
Valkyrie I|0|0|0|32|1
Valkyrie II|0|0|0|32|1
Vespa I|0|0|32|0|1
Vespa II|0|0|32|0|1
Warden I|0|0|64|0|1
Warden II|0|0|64|0|1
Warrior I|0|0|0|20|1
Warrior II|0|0|0|20|1
Wasp I|0|0|64|0|1
Wasp II|0|0|64|0|1
)", "`n", "`r") {
            fields := StrSplit(row, "|")
            total := fields[2] + fields[3] + fields[4] + fields[5]
            profiles[fields[1]] := {mix: [fields[2] / total, fields[3] / total, fields[4] / total, fields[5] / total], craft: fields[6] + 0}
        }
    }
}
